version:  '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '9999:3306'

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './apps/made-symfony/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/made-symfony/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}